# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "template-tests"
  # name: ${name}
  save_dir: ${original_work_dir}/logs/wandb
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  # entity: ""  # set to name of your wandb team
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
